### ISSUE TITLE
Kindly correct spelling of Imaginea in the folder from 'Imaginia'

### ISSUE THREAD

**Issue by hashd** [Roshan30/imagineaFirstATemplate#1]

**Comment by hashd** [comment]
Marking fixed

**Comment by Roshan30** [comment]
Hi Kiran,
            1) Add functionality is complete... I am adding a generic image
every time, otherwise i will have to write a different code to select image
from local and save it to the project folder.
           2) after adding the event page is getting redirected to home
page.
           3) Filter  search functionality is also complete.
          4) moved the controller functions to controller.js and all the
api calls to services.js. This is making controller.js much more clean. so
there are no calls to api from controller .js.

```
  Image changes, typography and color combination is remaining .I will
```

wrap these tasks by tomorrow.
     Functionality wise all the tasks are complete.

All changes are checked in.

Thanks.
Roshan.
